image: node:18.16.1

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - db.json

before_script:
  - npm install hexo-cli -g
  - test -e package.json && npm install

# Build stage - 构建网站
build:
  stage: build
  script:
    - hexo generate
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success

# Deploy stage - 部署到GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      when: on_success
